### ISSUE TITLE
Use that Chrome Extension : LEETHUB

### ISSUE THREAD

**Issue by Veeresh-R-G** [PavanNettam/The-LeetCode-Repo#1]
I highly recommend you to use this chrome extension Leethub
Link to the extension : [Click Here](https://chrome.google.com/webstore/detail/leethub/aciombdipochlnkbpcbgdpjffcfdbggi?hl=en)

Ok this is funny ... lol 🤣🤣🤣🤣🤣

**Comment by PavanNettam** [comment]
ok
